server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /chatapp {
        return 301 /chatapp/;
    }

    location /chatapp/ {
        try_files $uri $uri/ /chatapp/index.html;
    }
}